services:
  - name: credit-commons-node
    type: web
    env: node
    repo: https://github.com/creditcommons/credit-commons-node.git
    branch: main
    buildCommand: npm install
    startCommand: npm start

  - name: mysql
    type: mysql
    plan: free
    version: 5.7
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: 12345
      - key: MYSQL_DATABASE
        value: credit_commons_db

jobs:
  - name: setup-database
    type: cron
    env:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: credit_commons_db
      DATABASE_URL: ${mysql.internal_url}
    schedule: "@once"  # Runs once after the service is deployed
    command: |
      curl -o /tmp/sqlfile.sql https://your-repository-url/path/to/sqlfile.sql  # URL to your SQL file
      if ! mysql -u root -p$MYSQL_ROOT_PASSWORD -e "USE $MYSQL_DATABASE"; then
        echo "Database $MYSQL_DATABASE does not exist. Creating..."
        mysql -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE $MYSQL_DATABASE"
        mysql -u root -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE < /tmp/sqlfile.sql
      else
        echo "Database $MYSQL_DATABASE already exists."
      fi
